# permissions for end users to view vmgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmgroup-viewer-role
rules:
- apiGroups:
  - vmworld.tanzu.vmware.com.vmworld.tanzu.vmware.com
  resources:
  - vmgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmworld.tanzu.vmware.com.vmworld.tanzu.vmware.com
  resources:
  - vmgroups/status
  verbs:
  - get
